#!/usr/bin/env node
/*
 * Regenerates tools/audit/globals.json — the list of names the browser treats
 * as globals because index.html loads every js/ file as a plain script.
 *
 * A name counts as global if it is declared at the top level of any loaded
 * file, or assigned onto `window`. ESLint reads the output so `no-undef` can
 * tell a real typo apart from a legitimate cross-file reference.
 *
 * Run after adding a file or a new top-level declaration:
 *   node tools/audit/gen-globals.js
 */
const fs = require('fs');
const path = require('path');
const espree = require('espree');

const ROOT = path.resolve(__dirname, '..', '..');
const PARSE_OPTS = { ecmaVersion: 2022, sourceType: 'script', loc: true };

function walk(dir) {
  let out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out = out.concat(walk(p));
    else if (e.name.endsWith('.js')) out.push(p);
  }
  return out;
}

// Collect every binding introduced by a declarator pattern, so destructured
// top-level declarations (`const {a, b} = x`) are captured too.
function collectPattern(node, into) {
  if (!node) return;
  switch (node.type) {
    case 'Identifier':
      into.add(node.name);
      break;
    case 'ObjectPattern':
      for (const p of node.properties)
        collectPattern(p.type === 'RestElement' ? p.argument : p.value, into);
      break;
    case 'ArrayPattern':
      for (const el of node.elements) collectPattern(el, into);
      break;
    case 'AssignmentPattern':
      collectPattern(node.left, into);
      break;
    case 'RestElement':
      collectPattern(node.argument, into);
      break;
  }
}

// window.foo = ... anywhere in the file, including inside functions.
const WINDOW_PATTERN = /\bwindow\.([A-Za-z_$][\w$]*)\s*=(?!=)/g;

const names = new Set();
const files = walk(path.join(ROOT, 'js')).sort();
const failures = [];
// name -> files that declare it at top level. Two files declaring the same
// global is the "duplicate systems / race condition" failure mode, and no
// per-file linter can see it, so track it here.
const declaredIn = new Map();

for (const f of files) {
  const src = fs.readFileSync(f, 'utf8');
  const rel = path.relative(ROOT, f);

  let ast;
  try {
    ast = espree.parse(src, PARSE_OPTS);
  } catch (err) {
    failures.push(`${rel}:${err.lineNumber || '?'} ${err.message}`);
    continue;
  }

  const own = new Set();
  for (const node of ast.body) {
    if (node.type === 'VariableDeclaration') {
      for (const d of node.declarations) collectPattern(d.id, own);
    } else if (
      node.type === 'FunctionDeclaration' ||
      node.type === 'ClassDeclaration'
    ) {
      if (node.id) own.add(node.id.name);
    }
  }
  for (const n of own) {
    names.add(n);
    if (!declaredIn.has(n)) declaredIn.set(n, []);
    declaredIn.get(n).push(rel);
  }

  for (const m of src.matchAll(WINDOW_PATTERN)) names.add(m[1]);
}

const collisions = [...declaredIn.entries()]
  .filter(([, fl]) => fl.length > 1)
  .sort((a, b) => b[1].length - a[1].length);

if (failures.length) {
  console.error('Parse failures (globals from these files are missing):');
  for (const f of failures) console.error('  ' + f);
}

const sorted = [...names].sort();
const out = {
  _comment:
    'Generated by tools/audit/gen-globals.js — do not edit by hand. Each name is ' +
    'declared at the top level of some js/ file loaded by index.html, or assigned to window.',
  _fileCount: files.length,
  globals: sorted,
};

fs.writeFileSync(
  path.join(__dirname, 'globals.json'),
  JSON.stringify(out, null, 2) + '\n'
);
console.log(`globals.json: ${sorted.length} names from ${files.length} files`);

if (collisions.length) {
  console.log(
    `\n${collisions.length} global(s) declared at top level in more than one file:`
  );
  for (const [name, fl] of collisions) {
    console.log(`  ${name}  <-  ${fl.join(', ')}`);
  }
  console.log(
    'Whichever file loads last wins. Confirm each of these is intentional.'
  );
}

if (failures.length) process.exitCode = 1;
